INSERT INTO t_core_wk_panel(ID, TITLE, URL, VERSION, CREATEDBYID, CREATEDBYNAME, CREATEDTIME, CREATEDBYORGID, CREATEDBYORGNAME, LASTSUSPENDEDFLAG, LASTSUSPENDEDBYID, LASTSUSPENDEDBYNAME, LASTSUSPENDEDTIME, AUTHORITYCONTROL, TITLEDISPLAY) VALUES 
('20210716001', '我的待办', '/first/busicommon/page/my-todo', NULL, NULL, NULL, NULL, NULL, NULL, '0', NULL, NULL, NULL, '0', NULL);

INSERT INTO t_core_wk_panel(ID, TITLE, URL, VERSION, CREATEDBYID, CREATEDBYNAME, CREATEDTIME, CREATEDBYORGID, CREATEDBYORGNAME, LASTSUSPENDEDFLAG, LASTSUSPENDEDBYID, LASTSUSPENDEDBYNAME, LASTSUSPENDEDTIME, AUTHORITYCONTROL, TITLEDISPLAY) VALUES 
('20210716002', '各类检验情况统计', '/first/busicommon/page/inspection-statistic', NULL, NULL, NULL, NULL, NULL, NULL, '0', NULL, NULL, NULL, '0', NULL);

INSERT INTO t_core_wk_panel(ID, TITLE, URL, VERSION, CREATEDBYID, CREATEDBYNAME, CREATEDTIME, CREATEDBYORGID, CREATEDBYORGNAME, LASTSUSPENDEDFLAG, LASTSUSPENDEDBYID, LASTSUSPENDEDBYNAME, LASTSUSPENDEDTIME, AUTHORITYCONTROL, TITLEDISPLAY) VALUES 
('20210716003', '检验业务情况', '/first/busicommon/page/inspection-condition', NULL, NULL, NULL, NULL, NULL, NULL, '0', NULL, NULL, NULL, '0', NULL);

INSERT INTO t_core_wk_panel(ID, TITLE, URL, VERSION, CREATEDBYID, CREATEDBYNAME, CREATEDTIME, CREATEDBYORGID, CREATEDBYORGNAME, LASTSUSPENDEDFLAG, LASTSUSPENDEDBYID, LASTSUSPENDEDBYNAME, LASTSUSPENDEDTIME, AUTHORITYCONTROL, TITLEDISPLAY) VALUES 
('20210716004', '业务增长量', '/first/busicommon/page/business-growth', NULL, NULL, NULL, NULL, NULL, NULL, '0', NULL, NULL, NULL, '0', NULL);

INSERT INTO t_core_wk_panel(ID, TITLE, URL, VERSION, CREATEDBYID, CREATEDBYNAME, CREATEDTIME, CREATEDBYORGID, CREATEDBYORGNAME, LASTSUSPENDEDFLAG, LASTSUSPENDEDBYID, LASTSUSPENDEDBYNAME, LASTSUSPENDEDTIME, AUTHORITYCONTROL, TITLEDISPLAY) VALUES 
('20210716005', '销售市场情况', '/first/busicommon/page/sales-situation', NULL, NULL, NULL, NULL, NULL, NULL, '0', NULL, NULL, NULL, '0', NULL);

INSERT INTO t_core_wk_panel(ID, TITLE, URL, VERSION, CREATEDBYID, CREATEDBYNAME, CREATEDTIME, CREATEDBYORGID, CREATEDBYORGNAME, LASTSUSPENDEDFLAG, LASTSUSPENDEDBYID, LASTSUSPENDEDBYNAME, LASTSUSPENDEDTIME, AUTHORITYCONTROL, TITLEDISPLAY) VALUES 
('20210716006', '资源使用情况', '/first/busicommon/page/resource-usage', NULL, NULL, NULL, NULL, NULL, NULL, '0', NULL, NULL, NULL, '0', NULL);

INSERT INTO t_core_wk_panel(ID, TITLE, URL, VERSION, CREATEDBYID, CREATEDBYNAME, CREATEDTIME, CREATEDBYORGID, CREATEDBYORGNAME, LASTSUSPENDEDFLAG, LASTSUSPENDEDBYID, LASTSUSPENDEDBYNAME, LASTSUSPENDEDTIME, AUTHORITYCONTROL, TITLEDISPLAY) VALUES 
('20210716007', '同期发票增长对比', '/first/busicommon/page/invoice-growth', NULL, NULL, NULL, NULL, NULL, NULL, '0', NULL, NULL, NULL, '0', NULL);

INSERT INTO t_core_wk_panel(ID, TITLE, URL, VERSION, CREATEDBYID, CREATEDBYNAME, CREATEDTIME, CREATEDBYORGID, CREATEDBYORGNAME, LASTSUSPENDEDFLAG, LASTSUSPENDEDBYID, LASTSUSPENDEDBYNAME, LASTSUSPENDEDTIME, AUTHORITYCONTROL, TITLEDISPLAY) VALUES 
('20210716008', '各部门客户统计', '/first/busicommon/page/customer-statistics', NULL, NULL, NULL, NULL, NULL, NULL, '0', NULL, NULL, NULL, '0', NULL);

INSERT INTO t_core_wk_panel(ID, TITLE, URL, VERSION, CREATEDBYID, CREATEDBYNAME, CREATEDTIME, CREATEDBYORGID, CREATEDBYORGNAME, LASTSUSPENDEDFLAG, LASTSUSPENDEDBYID, LASTSUSPENDEDBYNAME, LASTSUSPENDEDTIME, AUTHORITYCONTROL, TITLEDISPLAY) VALUES 
('20210716009', '同期客户增长对比', '/first/busicommon/page/customer-growth', NULL, NULL, NULL, NULL, NULL, NULL, '0', NULL, NULL, NULL, '0', NULL);

INSERT INTO t_core_wk_panel(ID, TITLE, URL, VERSION, CREATEDBYID, CREATEDBYNAME, CREATEDTIME, CREATEDBYORGID, CREATEDBYORGNAME, LASTSUSPENDEDFLAG, LASTSUSPENDEDBYID, LASTSUSPENDEDBYNAME, LASTSUSPENDEDTIME, AUTHORITYCONTROL, TITLEDISPLAY) VALUES 
('20210716010', '仪器使用情况', '/first/busicommon/page/instrument-usage', NULL, NULL, NULL, NULL, NULL, NULL, '0', NULL, NULL, NULL, '0', NULL);

INSERT INTO t_core_wk_panel(ID, TITLE, URL, VERSION, CREATEDBYID, CREATEDBYNAME, CREATEDTIME, CREATEDBYORGID, CREATEDBYORGNAME, LASTSUSPENDEDFLAG, LASTSUSPENDEDBYID, LASTSUSPENDEDBYNAME, LASTSUSPENDEDTIME, AUTHORITYCONTROL, TITLEDISPLAY) VALUES 
('20210716011', '人员工作量情况', '/first/busicommon/page/staff-workload', NULL, NULL, NULL, NULL, NULL, NULL, '0', NULL, NULL, NULL, '0', NULL);

INSERT INTO t_core_wk_panel(ID, TITLE, URL, VERSION, CREATEDBYID, CREATEDBYNAME, CREATEDTIME, CREATEDBYORGID, CREATEDBYORGNAME, LASTSUSPENDEDFLAG, LASTSUSPENDEDBYID, LASTSUSPENDEDBYNAME, LASTSUSPENDEDTIME, AUTHORITYCONTROL, TITLEDISPLAY) VALUES 
('20210716012', '抽检情况', '/first/busicommon/page/sampling-inspection', NULL, NULL, NULL, NULL, NULL, NULL, '0', NULL, NULL, NULL, '0', NULL);

INSERT INTO t_core_wk_panel(ID, TITLE, URL, VERSION, CREATEDBYID, CREATEDBYNAME, CREATEDTIME, CREATEDBYORGID, CREATEDBYORGNAME, LASTSUSPENDEDFLAG, LASTSUSPENDEDBYID, LASTSUSPENDEDBYNAME, LASTSUSPENDEDTIME, AUTHORITYCONTROL, TITLEDISPLAY) VALUES 
('20210716013', '各部门发票统计', '/first/busicommon/page/invoice-dept-statistic', NULL, NULL, NULL, NULL, NULL, NULL, '0', NULL, NULL, NULL, '0', NULL);

INSERT INTO t_core_wk_panel(ID, TITLE, URL, VERSION, CREATEDBYID, CREATEDBYNAME, CREATEDTIME, CREATEDBYORGID, CREATEDBYORGNAME, LASTSUSPENDEDFLAG, LASTSUSPENDEDBYID, LASTSUSPENDEDBYNAME, LASTSUSPENDEDTIME, AUTHORITYCONTROL, TITLEDISPLAY) VALUES 
('20210716014', '各检所检验情况统计', '/first/busicommon/page/inspection-dept-statistic', NULL, NULL, NULL, NULL, NULL, NULL, '0', NULL, NULL, NULL, '0', NULL);

